### ISSUE TITLE
raspberry type

### ISSUE THREAD

**Issue by pilotak** [pithings/rpi-phantomjs#1]
Hi,
what was the raspberry pi you compiled it on? ARMv6 or v7, wheezy or jessie?

**Comment by thingspi** [comment]
Hello Pavel,
This was compiled on a Raspberry Pi 3, ARMv7, on Jessie.
Let me know if anything looks wrong!
Thanks,
Harvey

**Comment by pilotak** [comment]
Hello Harvey,
thanks for comming back. It would be a good idea to write it into README. Anyway i was interested about compiled version for ARMv6 Jessie for Raspberry A+/B+. Do you think you could do that for me or not really? perhaps you could post a manual how to do that

Thanks
Pavel
